apiVersion: v1
kind: Service
metadata:
  name: posts-srv # The name right here is going to be the name of the service.
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
